resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/lg456/flight-school
    branch: master
- name: staging-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: l3on_g@yahoo.com.au 
    password: H_(Zu_9XLGM?jD&>
    organization: flight-school
    space: development
jobs:
- name: test-app
  plan:
  - get: flight-school
  - task: tests
    file: flight-school/build.yml
  - put: staging-app
    params:
      manifest: flight-school/manifest.yml
